{
	"version": 1740656748,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/redlightgreenlighthowto-sheet0.png",
		"images/redlightgreenlighthowto-sheet1.png",
		"images/redlightgreenlighthowto-sheet2.png",
		"images/play-sheet0.png",
		"images/rickvsmortybg-sheet0.png",
		"images/greenportal-sheet0.png",
		"images/greenportal-sheet1.png",
		"images/greenportal-sheet2.png",
		"images/mortygood-sheet0.png",
		"images/mortygood-sheet1.png",
		"images/mortybad-sheet0.png",
		"images/mortybad-sheet1.png",
		"images/pickone-sheet0.png",
		"images/pickmorty-sheet0.png",
		"images/pickrick-sheet0.png",
		"images/sprite-sheet0.png",
		"images/p-sheet0.png",
		"images/particles.png",
		"media/tap.m4a",
		"media/tap.ogg",
		"media/appear.m4a",
		"media/appear.ogg",
		"media/button_click.m4a",
		"media/button_click.ogg",
		"media/go 2.m4a",
		"media/go 2.ogg",
		"media/go 1.m4a",
		"media/go 1.ogg",
		"media/teleport.m4a",
		"media/teleport.ogg",
		"media/rick vs. morty - bgm.m4a",
		"media/rick vs. morty - bgm.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}